// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  roomId: __t.u64().name("room_id"),
  posX: __t.f32().name("pos_x"),
  posY: __t.f32().name("pos_y"),
  posZ: __t.f32().name("pos_z"),
  yaw: __t.f32(),
  speed: __t.f32(),
  throttle: __t.f32(),
  steer: __t.f32(),
  frameId: __t.u32().name("frame_id"),
  color: __t.u32(),
  hpHull: __t.u16().name("hp_hull"),
  hpEngine: __t.u16().name("hp_engine"),
  gunYaw: __t.f32().name("gun_yaw"),
  gunPitch: __t.f32().name("gun_pitch"),
  lastFire: __t.timestamp().name("last_fire"),
  lastLoot: __t.timestamp().name("last_loot"),
  diedAt: __t.option(__t.timestamp()).name("died_at"),
});
