// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CargoItem = __t.object("CargoItem", {
  id: __t.u64(),
  tramplerId: __t.u64(),
  itemType: __t.u16(),
  qty: __t.u16(),
});
export type CargoItem = __Infer<typeof CargoItem>;

export const ExtractionBeacon = __t.object("ExtractionBeacon", {
  id: __t.u64(),
  roomId: __t.u64(),
  tramplerId: __t.u64(),
  endsAt: __t.timestamp(),
});
export type ExtractionBeacon = __Infer<typeof ExtractionBeacon>;

export const LootPoi = __t.object("LootPoi", {
  id: __t.u64(),
  roomId: __t.u64(),
  posX: __t.f32(),
  posZ: __t.f32(),
  itemType: __t.u16(),
  remaining: __t.u16(),
});
export type LootPoi = __Infer<typeof LootPoi>;

export const MountedGun = __t.object("MountedGun", {
  id: __t.u64(),
  roomId: __t.u64(),
  tramplerId: __t.u64(),
  slot: __t.u8(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  mannedBy: __t.option(__t.identity()),
  lastFire: __t.timestamp(),
});
export type MountedGun = __Infer<typeof MountedGun>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  roomId: __t.u64(),
  tramplerId: __t.option(__t.u64()),
  online: __t.bool(),
  localX: __t.f32(),
  localY: __t.f32(),
  localZ: __t.f32(),
});
export type Player = __Infer<typeof Player>;

export const Projectile = __t.object("Projectile", {
  id: __t.u64(),
  roomId: __t.u64(),
  shooter: __t.u64(),
  posX: __t.f32(),
  posY: __t.f32(),
  posZ: __t.f32(),
  velX: __t.f32(),
  velY: __t.f32(),
  velZ: __t.f32(),
  dmg: __t.u16(),
  spawned: __t.timestamp(),
});
export type Projectile = __Infer<typeof Projectile>;

export const Raider = __t.object("Raider", {
  identity: __t.identity(),
  roomId: __t.u64(),
  posX: __t.f32(),
  posZ: __t.f32(),
  yaw: __t.f32(),
  speed: __t.f32(),
  throttle: __t.f32(),
  steer: __t.f32(),
  buried: __t.bool(),
  boarding: __t.option(__t.u64()),
  boardProgress: __t.f32(),
  disarmDone: __t.bool(),
});
export type Raider = __Infer<typeof Raider>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  name: __t.string(),
  host: __t.identity(),
  createdAt: __t.timestamp(),
  maxPlayers: __t.u32(),
});
export type Room = __Infer<typeof Room>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const Trampler = __t.object("Trampler", {
  id: __t.u64(),
  owner: __t.identity(),
  roomId: __t.u64(),
  posX: __t.f32(),
  posY: __t.f32(),
  posZ: __t.f32(),
  yaw: __t.f32(),
  speed: __t.f32(),
  throttle: __t.f32(),
  steer: __t.f32(),
  frameId: __t.u32(),
  color: __t.u32(),
  hpHull: __t.u16(),
  hpEngine: __t.u16(),
  gunYaw: __t.f32(),
  gunPitch: __t.f32(),
  lastFire: __t.timestamp(),
  lastLoot: __t.timestamp(),
  diedAt: __t.option(__t.timestamp()),
  protectedUntil: __t.timestamp(),
  gunsDisabledUntil: __t.timestamp(),
});
export type Trampler = __Infer<typeof Trampler>;

export const Vault = __t.object("Vault", {
  identity: __t.identity(),
  salvage: __t.u32(),
  fortressUnlocked: __t.bool(),
  thopterUnlocked: __t.bool(),
});
export type Vault = __Infer<typeof Vault>;

