// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  tramplerId: __t.option(__t.u64()),
  online: __t.bool(),
  localX: __t.f32(),
  localY: __t.f32(),
  localZ: __t.f32(),
});
export type Player = __Infer<typeof Player>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const Trampler = __t.object("Trampler", {
  id: __t.u64(),
  owner: __t.identity(),
  posX: __t.f32(),
  posY: __t.f32(),
  posZ: __t.f32(),
  yaw: __t.f32(),
  speed: __t.f32(),
  throttle: __t.f32(),
  steer: __t.f32(),
  frameId: __t.u32(),
  hpHull: __t.u16(),
  hpEngine: __t.u16(),
});
export type Trampler = __Infer<typeof Trampler>;

